### ISSUE TITLE
handle multiple morphs in contacts example, possible bug causing missing CONTACT_ENDs

### ISSUE THREAD

**Issue by nosuchtim** [sensel/sensel-api#2] opened 2017-05-02 21:02 UTC
See the pull request I just submitted, which adds support for multiple morphs as well as making it easy to demonstrate a possible bug I've found.  Quick taps of three fingers will sometimes/often miss sending the CONTACT_ENDS for all of the contacts.  Seems to happen even with one Morph, though most of my testing is with 4 Morphs.  I changed the example to print a little more info (like the contact state, which reveals the bug), as well as turn LEDs on/off (which makes it easy to see when you've hit the bug).  I also changed it so that it runs forever until you hit control-C, which makes the example a lot more useful interactively.

**Comment by AlexSensel** [comment] 2017-05-16 00:48
Thank you for reporting the issue and example feedback. The bug was caused by turning on and off LEDs during scanning. The bug has been fixed in latest release of firmware (currently version 0.8.82). In the near future, we will adding your LED feedback to the contact example and will turn your multiple Sensel device code into a new example.

**Closed** 2017-05-16 00:49 UTC
